// L2: dynamic credential management (docs/credential-management.md): AK/SK generation/lookup/revocation + IStorageBackend persistence.
// Three-source model: static credentials (config file) = root; file credentials (credentials_file hot reload) and
// dynamic credentials (generated by this class) are data-plane only and may carry a per-credential policy (§10).
#pragma once

#include <atomic>
#include <chrono>
#include <filesystem>
#include <map>
#include <memory>
#include <optional>
#include <shared_mutex>
#include <string>
#include <string_view>
#include <vector>

#include "core/background.h"
#include "core/config.h"
#include "core/task.h"
#include "core/thread_pool.h"
#include "core/timer.h"
#include "core/util/crypto.h"
#include "s3/auth/sigv4.h"
#include "storage/backend.h"

namespace lights3::s3 {

enum class CredSource { kStatic, kFile, kDynamic };

// CredentialPolicy and parse_policy_json/policy_to_json live in s3/auth/policy.h
// (sigv4.h's verify snapshot needs them; placing them here would create a cycle with sigv4.h)

struct CredentialInfo {
    std::string access_key;
    util::SecretString secret_key;  // wiped on destruction (docs/archive/gaps.md §4)
    CredSource source = CredSource::kDynamic;
    std::string comment;
    std::chrono::system_clock::time_point created;
    std::optional<CredentialPolicy> policy;  // file/dynamic only; static credentials are always unrestricted
    // Edit propagation (roadmap §2.5): rev is a monotonic edit counter persisted in the
    // JSON (distinct from "version", which encodes the encryption format); storage_etag
    // is the credential object's ETag as last seen by this instance — sync re-reads an
    // AK only when the listed ETag differs, so policy edits propagate cheaply
    uint64_t rev = 1;
    std::string storage_etag;

    bool is_static() const { return source == CredSource::kStatic; }
};

// Reserved system bucket and object key prefix (docs/credential-management.md §4.1)
inline constexpr std::string_view kSysBucket = ".sys";
inline constexpr std::string_view kCredPrefix = "credentials/";

// Environment variable for the SK at-rest encryption master key (§10.1): 64 hex characters (32 bytes).
// Once set, newly written credential objects are version=2 (AES-256-GCM); v1 objects auto-upgrade at load
inline constexpr const char* kMasterKeyEnv = "LIGHTS3_MASTER_KEY";

class CredentialStore final : public ICredentialProvider {
public:
    // At startup, fully load .sys/credentials/* and credentials_file, merged with the static table
    // (same-AK priority static > file > dynamic, with a warning). A missing .sys counts as an empty table;
    // a single object with corrupt JSON is skipped with a warning; a v2 object with no master key / failed
    // decryption throws (a configuration error should block startup, not silently drop credentials and lock users out)
    static Task<std::shared_ptr<CredentialStore>> load(
        std::shared_ptr<storage::IStorageBackend> backend, const AuthConfig& cfg);

    ~CredentialStore() { shutdown_background(); }

    // ---- ICredentialProvider (verification hot path, read lock) ----
    // SK and policy snapshot returned in one call (docs/archive/gaps.md §3.7): dispatch's authorization uses the
    // snapshot returned by verify, so an in-flight revocation cannot make the policy vanish
    std::optional<CredentialLookup> lookup(std::string_view ak) const override;
    bool has_credentials() const override;

    bool is_root(std::string_view ak) const;

    // per-credential policy enforcement (§10.4): decided against the **current table**, rejection throws
    // S3Error(AccessDenied); static credentials / no policy always pass, and an empty ak (auth disabled) or
    // a lookup miss also passes. The request path no longer uses this (dispatch switched to the verify-time
    // snapshot, §3.7); kept for ops/tests to query the table directly
    void authorize(std::string_view ak, std::string_view bucket, std::string_view key,
                   Action action) const;

    // ---- Admin plane (docs/credential-management.md §5.1) ----
    // Write storage first, then memory (write-through): on crash, storage is authoritative and memory can at
    // worst have "less", never "more". Note: no co_await while holding a lock (a coroutine may resume on another
    // thread, and unlocking std::mutex across threads is UB); uniqueness of concurrent generate is guaranteed by the AK random space
    Task<CredentialInfo> generate(std::string comment,
                                  std::optional<CredentialPolicy> policy = std::nullopt);
    // Nonexistent -> InvalidAccessKeyId; static/file credentials -> MethodNotAllowed (managed by config/file)
    Task<void> remove(std::string_view ak);

    // In-place edit of a dynamic credential (roadmap §2.5): fields present are replaced
    // (set_policy + empty policy = clear). Write-through with a rev bump; other
    // instances pick the edit up via the sync ETag comparison. Same source rules as
    // remove (static/file -> MethodNotAllowed, missing -> InvalidAccessKeyId)
    struct Update {
        std::optional<std::string> comment;
        bool set_policy = false;
        std::optional<CredentialPolicy> policy;  // meaningful only when set_policy
    };
    Task<CredentialInfo> update(std::string_view ak, Update upd);

    std::optional<CredentialInfo> find(std::string_view ak) const;
    std::vector<CredentialInfo> list() const;  // sorted by AK

    // ---- Background tasks (§10.2 file hot-reload polling / §10.3 periodic multi-instance incremental sync) ----
    // Called once after main assembly; shutdown_background must be called before the thread pool joins (idempotent)
    void start_background(std::shared_ptr<ThreadPool> pool);
    void shutdown_background();

    // Manual hooks (tests/ops):
    // Re-read credentials_file immediately (ignoring mtime); a parse failure warns and keeps the old table
    void reload_file_now();
    // Do one .sys incremental sync immediately: new AKs are pulled into the table, vanished dynamic credentials are removed
    Task<void> sync_now();

    // The anti-fail-open empty-table guard has fired (README §1.2): when hot reload/sync tries to wipe a
    // non-empty table to empty, the old table is kept and this flag is set; /-/readyz turns 503 based on it.
    // The next successful load resets it
    bool degraded() const { return degraded_.load(std::memory_order_relaxed); }

private:
    CredentialStore() = default;

    void apply_file_credentials(std::vector<CredentialInfo> creds);
    Task<void> file_tick();
    Task<void> sync_tick();
    void schedule_file_reload();
    void schedule_sync();

    std::shared_ptr<storage::IStorageBackend> backend_;
    AuthConfig cfg_;
    std::optional<util::Aes256Key> master_key_;

    mutable std::shared_mutex mu_;
    std::map<std::string, CredentialInfo, std::less<>> creds_;
    // AKs this instance just revoked -> revocation time (guarded by mu_). sync_now's add branch skips recent
    // tombstones: when remove's delete_object interleaves with sync's list, the list may still see the revoked
    // object, and without a tombstone it would be pulled back into memory, resurrected for one sync cycle
    std::map<std::string, std::chrono::steady_clock::time_point, std::less<>> tombstones_;
    std::atomic<bool> degraded_{false};
    std::atomic<bool> sys_bucket_ready_{false};  // lazy create_bucket(".sys") happens only once

    // mtime snapshot of credentials_file (polling change detection; touched only by the background/manual reload thread)
    std::filesystem::file_time_type file_mtime_{};

    std::shared_ptr<ThreadPool> pool_;
    BackgroundTaskGroup bg_{"credential-store"};
    TimerQueue::Id file_timer_ = 0;
    TimerQueue::Id sync_timer_ = 0;
};

}  // namespace lights3::s3
