// L3: backup/restore and cross-engine migration for duostore meta
// (docs/archive/gaps.md §6.1). Logical dump/load mediated by IMetaStore: dump writes all
// bucket/object records (including extent manifests) and the sealed pack ledger
// into a self-describing binary stream; load replays them one by one through
// put_object — record-level replay naturally doubles as the meta migration tool
// between the four engines (rocksdb/sqlite/redis/tikv), with value-layout
// differences absorbed by the interface.
//
// Fixed backup/restore order (operational contract; the **load** side requires
// writes stopped; the dump side is online when the engine can snapshot —
// rocksdb/sqlite/tikv implement IMetaStore::snapshot(), redis cannot and keeps
// the writes-stopped requirement, roadmap §3.7):
//   Backup: data first (copy the chunks/packs directory or a rados pool snapshot)
//           -> then dump meta. The order guarantees "data referenced by meta is
//           necessarily in the backup" (§6 data-first mirror argument): extra
//           files on the data side are merely orphans; the reverse does not hold.
//           An online dump keeps the same argument: the snapshot is taken after
//           the data copy, so anything it references was already on disk.
//   Restore: put data back first -> load meta -> **forced orphan scan**
//           (built into DuoStoreBackend::run_meta_load) — reclaims files the data
//           side accumulated during the backup window.
//
// State deliberately not archived (converged by existing mechanisms after
// restore):
//   - In-progress multipart: upload_id is generated by the target engine and
//     cannot be preserved; resuming across a migration could never work anyway.
//     Its part data is unreferenced on the restore side -> reclaimed by the
//     orphan scan.
//   - gcq pending-reclaim ledger: the interface has no enqueue primitive; those
//     extents are unreferenced on the restore side -> same fallback as above.
//   - Bucket creation time: re-stamped by create_bucket (informational field, no
//     S3 semantics depend on it).
//   - Object version: restarted by put_object on the target side (only used by
//     runtime compaction CAS, no persistent semantics).
// The ledger of unsealed packs is rebuilt as delta rows by object replay; sealed
// state and file_size are restored from 'S' records, and fully dead packs (no
// object references) restore as a sealed ledger entry with live=0 -> deleted
// wholesale by the next GC round.
#pragma once

#include <cstdint>
#include <iosfwd>

#include "storage/duostore/meta_store.h"

namespace lights3::storage::duostore {

struct MetaDumpStats {
    uint64_t buckets = 0;
    uint64_t objects = 0;
    uint64_t sealed_packs = 0;
};

// Full export to out. src should be a point-in-time snapshot view
// (IMetaStore::snapshot()) for an online dump; when passed a live store the
// caller must guarantee no concurrent writes (the backend-layer entry point
// additionally holds the GC mutex either way). The stream carries its own
// magic, per-record length prefixes, and trailing counts + crc32c — the load
// side validates all of it
MetaDumpStats dump_meta(IMetaReadView& src, std::ostream& out);

// Replay from in into dst (should be a freshly created empty store; buckets that
// already exist are skipped idempotently, supporting a rerun after interruption).
// At the end, raises the chunk/pack file-number counters above the largest id
// seen — preventing post-restore new writes from allocating ids that collide with
// existing files. Truncated stream / crc mismatch / count mismatch throw
// InternalError
MetaDumpStats load_meta(IMetaStore& dst, std::istream& in);

}  // namespace lights3::storage::duostore
