# Build-time version stamp (roadmap §6.3): run in script mode (-P) from the
# lights3_version_gen custom target on every build, so the embedded git commit
# tracks the checkout instead of the last configure. The file is rewritten only
# when its content changes, which keeps the version object out of incremental
# rebuilds that did not move HEAD.
#
# Inputs (-D): LIGHTS3_VERSION, SOURCE_DIR, OUTPUT, BUILD_TYPE,
#              GIT_COMMIT_OVERRIDE (optional: tarball / Docker builds without .git)
if(NOT LIGHTS3_VERSION OR NOT SOURCE_DIR OR NOT OUTPUT)
  message(FATAL_ERROR "GenerateVersion.cmake needs LIGHTS3_VERSION, SOURCE_DIR and OUTPUT")
endif()

set(commit "unknown")
if(GIT_COMMIT_OVERRIDE)
  set(commit "${GIT_COMMIT_OVERRIDE}")
else()
  find_package(Git QUIET)
  if(GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
      OUTPUT_VARIABLE head OUTPUT_STRIP_TRAILING_WHITESPACE
      RESULT_VARIABLE rc ERROR_QUIET)
    if(rc EQUAL 0 AND head)
      set(commit "${head}")
      # Uncommitted changes to tracked files mark the build as dirty; untracked
      # files are ignored so scratch build directories do not taint the stamp
      execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" diff-index --quiet HEAD --
        RESULT_VARIABLE dirty_rc ERROR_QUIET)
      if(NOT dirty_rc EQUAL 0)
        set(commit "${commit}-dirty")
      endif()
    endif()
  endif()
endif()

if(NOT BUILD_TYPE)
  set(BUILD_TYPE "unknown")
endif()
string(TIMESTAMP build_date "%Y-%m-%d" UTC)

set(content "// Generated by cmake/GenerateVersion.cmake -- do not edit, do not commit
namespace lights3::build_info {
extern const char* const version = \"${LIGHTS3_VERSION}\";
extern const char* const git_commit = \"${commit}\";
extern const char* const build_type = \"${BUILD_TYPE}\";
extern const char* const build_date = \"${build_date}\";
}  // namespace lights3::build_info
")

set(previous "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
